bedroom_choices = {
  '1':1,
  '2':2,
  '3':3,
  '4':4,
  '5':5,
  '6':6,
  '7':7,
  '8':8,
  '9':9,
  '10':10
  }

price_choices = {
  '1000000':'1,000,000',
  '2000000':'2,000,000',
  '3000000':'3,000,000',
  '4000000':'4,000,000',
  '5000000':'5,000,000',
  '6000000':'6,000,000',
  '7000000':'7,000,000',
  '8000000':'8,000,000',
  '9000000':'9,000,000',
  '10000000':'10M+',
}

state_choices = {
        '01': 'Республика Адыгея',
        '02': 'Республика Башкортостан',
        '03': 'Республика Бурятия',
        '04': 'Республика Алтай',
        '05': 'Республика Дагестан',
        '06': 'Республика Ингушетия',
        '07': 'Кабардино-Балкарская Республика',
        '08': 'Республика Калмыкия',
        '09': 'Карачаево-Черкесская Республика',
        '10': 'Республика Карелия',
        '11': 'Республика Коми',
        '12': 'Республика Марий Эл',
        'GU': 'Guam',
        'HI': 'Hawaii',
        'IA': 'Iowa',
        'ID': 'Idaho',
        'IL': 'Illinois',
        'IN': 'Indiana',
        'KS': 'Kansas',
        'KY': 'Kentucky',
        'LA': 'Louisiana',
        'MA': 'Massachusetts',
        'MD': 'Maryland',
        'ME': 'Maine',
        'MI': 'Michigan',
        'MN': 'Minnesota',
        'MO': 'Missouri',
        'MP': 'Northern Mariana Islands',
        'MS': 'Mississippi',
        'MT': 'Montana',
        'NA': 'National',
        'NC': 'North Carolina',
        'ND': 'North Dakota',
        'NE': 'Nebraska',
        'NH': 'New Hampshire',
        'NJ': 'New Jersey',
        'NM': 'New Mexico',
        'NV': 'Nevada',
        'NY': 'New York',
        'OH': 'Ohio',
        'OK': 'Oklahoma',
        'OR': 'Oregon',
        'PA': 'Pennsylvania',
        'PR': 'Puerto Rico',
        'RI': 'Rhode Island',
        'SC': 'South Carolina',
        'SD': 'South Dakota',
        'TN': 'Tennessee',
        'TX': 'Texas',
        'UT': 'Utah',
        'VA': 'Virginia',
        'VI': 'Virgin Islands',
        'VT': 'Vermont',
        'WA': 'Washington',
        'WI': 'Wisconsin',
        'WV': 'West Virginia',
        'WY': 'Wyoming'
}